namespace: kvcluster
bases: 
 - ../base

patchesStrategicMerge:
  - manager_image_patch.yaml
  - manager_tenant_kubeconfig_secret_patch.yaml

patchesJson6902:
- patch: |-
    - op: add
      path: /metadata/namespace
      value: kube-system
    - op: add
      path: /subjects/0/namespace
      value: kvcluster
  target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: kccm

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: cloud-config
  namespace: default
  files:
  - cloud-config

secretGenerator:
- name: kubeconfig
  namespace: default
  files:
  - value=kubeconfig

